# Generated by Django 4.2.6 on 2023-10-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skills",
            options={"verbose_name": "Skill", "verbose_name_plural": "Skills"},
        ),
    ]
