# Generated by Django 4.2.6 on 2023-10-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_alter_skills_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="education",
            options={"verbose_name": "Education", "verbose_name_plural": "EducationS"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "Project", "verbose_name_plural": "Projects"},
        ),
    ]
