# Generated by Django 4.2.6 on 2023-10-14 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_alter_education_options_alter_project_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home",
            old_name="Name",
            new_name="name",
        ),
    ]
