# Generated by Django 4.2.1 on 2023-10-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0004_rename_name_home_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="home",
            name="picture",
        ),
        migrations.AlterField(
            model_name="about",
            name="career",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="about",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
