# Generated by Django 4.2.6 on 2023-10-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0005_remove_home_picture_alter_about_career_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='cv',
            field=models.FileField(default='False', upload_to='cv_files/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='greetings2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(max_length=10),
        ),
    ]
