# Generated by Django 4.2.6 on 2023-10-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0007_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='education',
            name='university',
        ),
        migrations.RemoveField(
            model_name='education',
            name='updated',
        ),
        migrations.AddField(
            model_name='education',
            name='date',
            field=models.TextField(default='Description par défaut', max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(default='Description par défaut', max_length=500),
        ),
        migrations.AddField(
            model_name='education',
            name='title',
            field=models.CharField(default='Description par défaut', max_length=100),
        ),
        migrations.DeleteModel(
            name='Competence',
        ),
    ]
