# Generated by Django 4.2.6 on 2023-10-15 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0008_remove_education_academic_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='en_cours',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='education',
            name='projet',
            field=models.TextField(default='Description du projet par défaut', max_length=500),
        ),
    ]
