# Generated by Django 4.2.6 on 2023-10-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0009_education_en_cours_education_projet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='projet',
            field=models.TextField(blank=True, default='Description du projet par défaut', max_length=500, null=True),
        ),
    ]
