# Generated by Django 4.2.6 on 2023-10-15 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0013_project_en_cours_alter_project_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
    ]
