# Generated by Django 4.2.6 on 2023-10-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0014_remove_project_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.TextField(default='Description par défaut', max_length=500),
        ),
    ]
