# Generated by Django 4.2.6 on 2023-10-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0015_project_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='experienceprofessionnelle',
            name='description',
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(default='position par défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.TextField(default='Date par défaut', max_length=500),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(default='titrepar défaut', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.TextField(default='Date par défaut', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='name_project',
            field=models.CharField(default='nom  par défaut', max_length=100),
        ),
    ]
