# Generated by Django 4.2.6 on 2023-10-15 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0016_remove_education_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobetudiant',
            name='description',
        ),
    ]
