# Generated by Django 4.2.1 on 2023-10-18 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0019_skills_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="description",
            field=models.TextField(default="Description par défaut", max_length=1000),
        ),
    ]
