# Generated by Django 4.2.6 on 2023-10-19 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cv", "0020_alter_project_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contact_me",
            old_name="messgae",
            new_name="message",
        ),
    ]
